{
  "openapi" : "3.0.0",
  "info" : {
    "title" : "Hello World API",
    "description" : "Esta es una API para demostración",
    "contact" : {
      "email" : "hello.world@arahant.life"
    },
    "license" : {
      "name" : "Apache 2.0",
      "url" : "http://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "version" : "1.17.0"
  },
  "servers" : [ {
    "url" : "https://virtserver.swaggerhub.com/IVANFERREIRA/HelloWorld/1.17.0",
    "description" : "SwaggerHub API Auto Mocking"
  }, {
    "url" : "https://virtserver.swaggerhub.com/HelloWorld/1.17.0",
    "description" : "Hello World Test API"
  } ],
  "tags" : [ {
    "name" : "admins",
    "description" : "Peticiones asegurdads exclusivas para administradores"
  }, {
    "name" : "developers",
    "description" : "Operations disponibles a todos los desarrolladores"
  } ],
  "paths" : {
    "/inventory" : {
      "get" : {
        "tags" : [ "developers" ],
        "summary" : "Buscan en el inventario",
        "description" : "Con los argumentos apropiados, puede buscar ítems la disponibilidad de ítems en el inventario\n",
        "operationId" : "searchInventory",
        "parameters" : [ {
          "name" : "searchString",
          "in" : "query",
          "description" : "puede agregar una palabra de búsqueda opcional para buscar en el inventario",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "string"
          }
        }, {
          "name" : "skip",
          "in" : "query",
          "description" : "número de registros a saltear para la paginación",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "minimum" : 0,
            "type" : "integer",
            "format" : "int32"
          }
        }, {
          "name" : "limit",
          "in" : "query",
          "description" : "límite del número máximo de resultados",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "maximum" : 50,
            "minimum" : 0,
            "type" : "integer",
            "format" : "int32"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "resultados que coinciden con el criterio de búsqueda",
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "array",
                  "items" : {
                    "$ref" : "#/components/schemas/InventoryItem"
                  }
                }
              }
            }
          },
          "400" : {
            "description" : "parámetro de entrada incorrecto"
          }
        }
      },
      "post" : {
        "tags" : [ "admins" ],
        "summary" : "Agrega un ítem al inventario",
        "description" : "Agrega el ítem especificado al sistema de inventario",
        "operationId" : "addInventory",
        "requestBody" : {
          "description" : "Item de inventario a ser agregado",
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/InventoryItem"
              }
            }
          }
        },
        "responses" : {
          "201" : {
            "description" : "ítem creado"
          },
          "400" : {
            "description" : "entrada inválida, objeto inválido"
          },
          "409" : {
            "description" : "el ítem ya existe"
          }
        }
      }
    }
  },
  "components" : {
    "schemas" : {
      "InventoryItem" : {
        "required" : [ "id", "manufacturer", "name", "releaseDate" ],
        "type" : "object",
        "properties" : {
          "id" : {
            "type" : "string",
            "format" : "uuid",
            "example" : "d290f1ee-6c54-4b01-90e6-d701748f0851"
          },
          "name" : {
            "type" : "string",
            "example" : "Cable de fibra óptica 25m OM-5 LC-LC"
          },
          "releaseDate" : {
            "type" : "string",
            "format" : "date-time",
            "example" : "2016-08-29T09:12:33.001Z"
          },
          "manufacturer" : {
            "$ref" : "#/components/schemas/Manufacturer"
          }
        }
      },
      "Manufacturer" : {
        "required" : [ "name" ],
        "type" : "object",
        "properties" : {
          "name" : {
            "type" : "string",
            "example" : "Arahant Life"
          },
          "homePage" : {
            "type" : "string",
            "format" : "url",
            "example" : "https://www.arahant.life"
          },
          "phone" : {
            "type" : "string",
            "example" : "+595 991 555 555"
          }
        }
      }
    }
  }
}